[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino

; 库依赖
lib_deps = 
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^6.19.4
    https://github.com/Chris--A/Keypad.git

; 串口配置
monitor_speed = 115200

; 编译优化
build_flags = 
    -Wall
    -Wextra
